fail fast if ip address is not set

diff --git a/.github/workflows/acc-tests.yaml b/.github/workflows/acc-tests.yaml
--- a/.github/workflows/acc-tests.yaml
+++ b/.github/workflows/acc-tests.yaml
@@ -21,9 +21,13 @@ jobs:
         cache: true
     - name: Get IP
       id: getip
-      run: echo "ip_address=$(curl -s https://api.ipify.org)" >> "$GITHUB_OUTPUT"
+      run: echo "ip_address=$(curl -s https://api.ipify.org?format=json | jq -r .ip)" >> "$GITHUB_OUTPUT"
     - name: Check IP
-      run: echo "${{ steps.getip.outputs.ip_address }}"
+      run: |
+        if [[ -z "${{ steps.getip.outputs.ip_address }}" ]]; then
+          echo "Unable to get runner IP address. Cannot update Network Permission List for acceptance tests."
+          exit 1
+        fi
     - name: Run Acceptance Tests
       env:
         ATLAS_ALLOWLIST_IP: ${{ steps.getip.outputs.ip_address }}
